version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root1234
      - DB_NAME=aicc_db_map
    volumes:
      - ./server:/app
    depends_on:
      database:
        condition: service_healthy  # 수정된 부분
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always  # 추가된 부분

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    restart: always  # 추가된 부분

  database:
    build:
      context: ./map_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: aicc_db_map
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
