# Base image로 MariaDB 사용
FROM mariadb:latest

# Python 3.11 설치를 위한 의존성 설치
RUN apt-get update && apt-get install -y \
    curl \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-venv python3.11-dev && \
    apt-get clean

# pip 설치
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11

# Python 환경 설정 및 라이브러리 설치
RUN python3.11 -m venv /opt/pyenv && \
    /opt/pyenv/bin/pip install --upgrade pip && \
    /opt/pyenv/bin/pip install finance-datareader==0.9.93 \
    plotly==5.23.0 \
    yfinance==0.2.41 \
    fredapi==0.5.2 \
    pymysql==1.1.1 \
    openpyxl

# 환경 변수 설정 (Python을 사용하기 위한 경로 추가)
ENV PATH="/opt/pyenv/bin:$PATH"

# 작업 디렉토리 설정
WORKDIR /docker-entrypoint-initdb.d

# Python 스크립트와 데이터 폴더를 컨테이너로 복사
COPY MAP_project_DATABASE.py /docker-entrypoint-initdb.d/
COPY ./datas /docker-entrypoint-initdb.d/datas

# MariaDB 서버 시작 및 Python 초기화 스크립트 실행
CMD ["bash", "-c", "\
exec mariadbd --skip-networking & \
until mysqladmin ping -h localhost --silent; do \
  echo 'waiting for MariaDB to be up...'; \
  sleep 5; \
done; \
python /docker-entrypoint-initdb.d/MAP_project_DATABASE.py; \
exec mariadbd"]
