FROM python:3.11.9

WORKDIR /usr/src/app

RUN pip install --upgrade pip

COPY requirements.txt ./
RUN pip install -r requirements.txt

RUN pip install notebook nbconvert

COPY . .

RUN apt-get update && apt-get install -y \
    libmariadb-dev \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 3306

CMD ["jupyter", "notebook", "--to", "notebook", "--execute", "make_sample_data.ipynb", "data_to_excel.ipynb", "MAP_project_DATABASE.ipynb"]
