# Node.js 이미지 사용
FROM node:18

# 작업 디렉토리 설정
WORKDIR /app

# MySQL 클라이언트 도구 설치
RUN apt-get update && apt-get install -y default-mysql-client

# 패키지 파일 복사 및 설치
COPY package*.json ./
RUN npm install && npm install nodemailer

# 모델과 스크립트 파일 복사
COPY ./src/algorithm /app

# 추가 필요한 스크립트 또는 모델 파일 복사
# COPY ./src/algorithm/model.h5 /app

# entrypoint.sh 파일을 작업 디렉토리에 복사하고 실행 권한 부여
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# 포트 설정
EXPOSE 5000

# Entrypoint 설정
ENTRYPOINT ["/app/entrypoint.sh"]
