# Python 3.11.9 이미지를 사용합니다.
FROM python:3.11.9-slim

# 작업 디렉토리 설정
WORKDIR /app

# 시스템 의존성 설치
RUN apt-get update && apt-get install -y curl build-essential gcc g++ && rm -rf /var/lib/apt/lists/*

# pip 최신화
RUN pip install --no-cache-dir --upgrade pip

# 필요한 라이브러리 설치
RUN pip install --no-cache-dir \
    numpy==1.24.3 \
    pandas==2.0.3 \
    tensorflow==2.16.2 \
    scikit-learn==1.3.0

# Node.js 설치
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs

# 모델과 스크립트 파일 복사
COPY ./src/algorithm /app

# 필요한 경우 추가 스크립트 또는 모델 파일 복사
# COPY ./src/algorithm/model.h5 /app

# entrypoint.sh 파일을 작업 디렉토리에 복사하고 실행 권한 부여
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Entrypoint 설정
ENTRYPOINT ["/app/entrypoint.sh"]
