# 1 워크플로의 이름 지정
name: CI

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정

    # 4 실행 스텝 지정
    steps:
      # 4.1 리포지토리 체크아웃
      - uses: actions/checkout@v3

      # 4.2 Docker 셋업
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4.3 Docker 로그인 (Docker Hub 사용 시)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4.4 Docker 빌드 및 푸시
      - name: Build and Push Docker Images
        run: |
          docker-compose -f ./docker-compose.yml build  # Docker Compose 파일로 Docker 이미지 빌드
          docker-compose -f ./docker-compose.yml up -d  # 컨테이너 실행

      # 4.5 컨테이너 상태 확인
      - name: Check Docker Compose Services
        run: |
          docker-compose -f ./docker-compose.yml ps

      # 4.6 (옵션) Docker Compose 정리
      - name: Teardown Docker Compose
        if: always()
        run: docker-compose -f ./docker-compose.yml down
